spring.application.name=the_full_web_api
server.port=8090

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://the-full-db.c7qw8eqkk298.ap-southeast-2.rds.amazonaws.com:3306/the_full_web?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

spring.datasource.username=
spring.datasource.password=
spring.sql.init.mode=never

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

mybatis.mapper-locations=classpath:mybatis-mapper/**/*.xml
mybatis.type-aliases-package=com.thefullweb.api.domain.contact,com.thefullweb.api.domain.promotion
mybatis.configuration.map-underscore-to-camel-case=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

google.cloud.vision.credentials.path=

documentai.project.id=
documentai.location=
#documentai.processor.id=

openai.api.key=

logging.level.root=info
logging.level.com.example=debug
logging.level.org.springframework.jdbc=debug
logging.level.org.mybatis=debug
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG

# 운영 비밀 정보는 서버 외부 파일에서 주입
spring.config.import=optional:file:/opt/thefull-api-config/application-secret-real.properties

file.upload-dir=/opt/thefull-web/uploads/image/

instagram.access-token=

erp.webhook.secret=

erp.internal-api.secret=

# smtp 설정
contact.reply.smtp.host=
contact.reply.smtp.port=
contact.reply.smtp.secure=
contact.reply.smtp.user-domain=
contact.reply.mail.from-display-name=
